/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lavanderia;

import java.awt.Color;

/**
 *
 * @author Aspharr17
 */
public class InterfazLavanderia extends javax.swing.JFrame {
    int NLavadoras=1;  //#Lavadoras y secadoras
    int NSecadoras=1;

    /**
     * Creates new form InterfazLavanderia
     */
    public InterfazLavanderia() {
        initComponents();
        ShowL();
        ShowS();        
    }
    public void ShowL(){
   
        switch(NLavadoras){
          
            case 1:
                L1.setVisible(true);
                L2.setVisible(false);
                L3.setVisible(false);
                L4.setVisible(false);
                L5.setVisible(false);
                break;
            case 2:
                L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(false);
                L4.setVisible(false);
                L5.setVisible(false);
                break;
            case 3:
                L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(false);
                L5.setVisible(false);
                break;
             case 4:
                L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(false);
                break;
              case 5:
                L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                break;
        
                
        }
    
    }
    public void ShowS(){
        
        switch(NSecadoras){
          
            case 1:
                S1.setVisible(true);
               // S1.setBackground(Color.green);
                S2.setVisible(false);
                S3.setVisible(false);
                S4.setVisible(false);
                S5.setVisible(false);
                break;
            case 2:
                S1.setVisible(true);
                S2.setVisible(true);
                S3.setVisible(false);
                S4.setVisible(false);
                S5.setVisible(false);
                break;
            case 3:
                S1.setVisible(true);
                S2.setVisible(true);
                S3.setVisible(true);
                S4.setVisible(false);
                S5.setVisible(false);
                break;
             case 4:
                S1.setVisible(true);
                S2.setVisible(true);
                S3.setVisible(true);
                S4.setVisible(true);
                S5.setVisible(false);
                break;
              case 5:
                S1.setVisible(true);
                S2.setVisible(true);
                S3.setVisible(true);
                S4.setVisible(true);
                S5.setVisible(true);
                break;
        
                
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JButton();
        AddLavadora = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        AddSecadora = new javax.swing.JButton();
        InputTimeM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DeleteLavadora = new javax.swing.JButton();
        DeleteSecadora = new javax.swing.JButton();
        CronoMin = new javax.swing.JTextField();
        L1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        L2 = new javax.swing.JButton();
        L3 = new javax.swing.JButton();
        L4 = new javax.swing.JButton();
        L5 = new javax.swing.JButton();
        S1 = new javax.swing.JButton();
        S2 = new javax.swing.JButton();
        S3 = new javax.swing.JButton();
        S4 = new javax.swing.JButton();
        S5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CronoH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InputTimeH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CSS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CLS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CTS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Start.setText("Iniciar");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        AddLavadora.setText("Agregar Lavadora");
        AddLavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLavadoraActionPerformed(evt);
            }
        });

        AddSecadora.setText("Agregar Secadoras");
        AddSecadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSecadoraActionPerformed(evt);
            }
        });

        InputTimeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTimeMActionPerformed(evt);
            }
        });

        jLabel1.setText("Tiempo");

        DeleteLavadora.setText("Eliminar Lavadora");
        DeleteLavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLavadoraActionPerformed(evt);
            }
        });

        DeleteSecadora.setText("Eliminar Secadora");
        DeleteSecadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSecadoraActionPerformed(evt);
            }
        });

        CronoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CronoMinActionPerformed(evt);
            }
        });

        L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/508628.png"))); // NOI18N
        L1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Maximo 5");

        L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/508628.png"))); // NOI18N
        L2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2ActionPerformed(evt);
            }
        });

        L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/508628.png"))); // NOI18N
        L3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3ActionPerformed(evt);
            }
        });

        L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/508628.png"))); // NOI18N
        L4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4ActionPerformed(evt);
            }
        });

        L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/508628.png"))); // NOI18N
        L5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5ActionPerformed(evt);
            }
        });

        S1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/tumble-dryer.png"))); // NOI18N
        S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1ActionPerformed(evt);
            }
        });

        S2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/tumble-dryer.png"))); // NOI18N
        S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2ActionPerformed(evt);
            }
        });

        S3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/tumble-dryer.png"))); // NOI18N
        S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3ActionPerformed(evt);
            }
        });

        S4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/tumble-dryer.png"))); // NOI18N
        S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S4ActionPerformed(evt);
            }
        });

        S5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lavanderia/tumble-dryer.png"))); // NOI18N
        S5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Reloj");

        CronoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CronoHActionPerformed(evt);
            }
        });

        jLabel4.setText(":");

        InputTimeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTimeHActionPerformed(evt);
            }
        });

        jLabel5.setText("Cola Lavadoras");

        CSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSSActionPerformed(evt);
            }
        });

        jLabel6.setText("Cola Secadoras");

        CLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLSActionPerformed(evt);
            }
        });

        jLabel7.setText("Cargas Terminadas");

        CTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddLavadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputTimeM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteLavadora)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addGap(315, 315, 315))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteSecadora, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddSecadora)
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InputTimeH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(CronoH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CronoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(CSS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(S3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(CTS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(CLS)
                    .addGap(574, 574, 574)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CronoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CronoH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1)
                    .addComponent(S1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L2)
                            .addComponent(S2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L3)
                            .addComponent(S3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L4)
                            .addComponent(S4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddLavadora)
                                    .addComponent(AddSecadora)
                                    .addComponent(InputTimeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(InputTimeH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeleteLavadora)
                                    .addComponent(DeleteSecadora))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)))
                        .addComponent(Start))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(S5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(CLS)
                    .addGap(318, 318, 318)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        
        Lavanderia objeto = new Lavanderia(Start,CronoMin,CronoH,InputTimeM, InputTimeH,
                AddLavadora,AddSecadora,DeleteLavadora,DeleteSecadora,NLavadoras,NSecadoras,
                CLS,CSS,L1,L2,L3,L4,L5,S1,S2,S3,S4,S5,CTS);
        objeto.start();
    }//GEN-LAST:event_StartActionPerformed

    private void AddLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLavadoraActionPerformed
        // TODO add your handling code here:
         NLavadoras++;
         if(NLavadoras!=5){
         AddLavadora.setEnabled(true);
         }
         if(NLavadoras!=1){
         DeleteLavadora.setEnabled(true);
         }
         if(NLavadoras==5){
         AddLavadora.setEnabled(false);
         }
         ShowL();
         
        
    }//GEN-LAST:event_AddLavadoraActionPerformed

    private void InputTimeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTimeMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTimeMActionPerformed

    private void CronoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CronoMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CronoMinActionPerformed

    private void DeleteLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLavadoraActionPerformed
        // TODO add your handling code here:
          NLavadoras--;
       if(NLavadoras!=5){
         AddLavadora.setEnabled(true);
         }
         if(NLavadoras!=1){
         DeleteLavadora.setEnabled(true);
         }
         if(NLavadoras==1){
         DeleteLavadora.setEnabled(false);
         AddLavadora.setEnabled(true);
         }
         ShowL();
         

    }//GEN-LAST:event_DeleteLavadoraActionPerformed

    private void AddSecadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSecadoraActionPerformed
        // TODO add your handling code here:
           NSecadoras++;
           
         if(NSecadoras!=5){
         AddSecadora.setEnabled(true);
         }
         if(NSecadoras!=1){
         DeleteSecadora.setEnabled(true);
         }
         if(NSecadoras==5){
         AddSecadora.setEnabled(false);
         }
         ShowS();
  

    }//GEN-LAST:event_AddSecadoraActionPerformed

    private void DeleteSecadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSecadoraActionPerformed
        // TODO add your handling code here:
           NSecadoras--; 
           if(NSecadoras!=5){
         AddSecadora.setEnabled(true);
         }
         if(NSecadoras!=1){
         DeleteSecadora.setEnabled(true);
         }
         if(NSecadoras==1){
         DeleteSecadora.setEnabled(false);
         AddSecadora.setEnabled(true);
         }
         ShowS();

    }//GEN-LAST:event_DeleteSecadoraActionPerformed

    private void L1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L1ActionPerformed

    private void L2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2ActionPerformed

    private void L3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3ActionPerformed

    private void L4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L4ActionPerformed

    private void L5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L5ActionPerformed

    private void S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S1ActionPerformed

    private void S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S2ActionPerformed

    private void S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S3ActionPerformed

    private void S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S4ActionPerformed

    private void S5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S5ActionPerformed

    private void CronoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CronoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CronoHActionPerformed

    private void InputTimeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTimeHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTimeHActionPerformed

    private void CSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSSActionPerformed

    private void CLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLSActionPerformed

    private void CTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLavanderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLavanderia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLavadora;
    private javax.swing.JButton AddSecadora;
    private javax.swing.JTextField CLS;
    private javax.swing.JTextField CSS;
    private javax.swing.JTextField CTS;
    private javax.swing.JTextField CronoH;
    private javax.swing.JTextField CronoMin;
    private javax.swing.JButton DeleteLavadora;
    private javax.swing.JButton DeleteSecadora;
    private javax.swing.JTextField InputTimeH;
    private javax.swing.JTextField InputTimeM;
    private javax.swing.JButton L1;
    private javax.swing.JButton L2;
    private javax.swing.JButton L3;
    private javax.swing.JButton L4;
    private javax.swing.JButton L5;
    private javax.swing.JButton S1;
    private javax.swing.JButton S2;
    private javax.swing.JButton S3;
    private javax.swing.JButton S4;
    private javax.swing.JButton S5;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
